swagger: '2.0'
info:
  version: "0.0.1"
  title: MarketplaceCore Database Rest API
  contact:
    name: TRUMPF Werkzeugmaschinen GmbH & Co KG
  description: TODOS - Offers, OfferRequest, Payment
paths:
  
  /users:
    get:
      description: gets all Users. Only for Admin Role avaiable
      parameters:
        - name: userUUID
          in: query
          description: system client userid
          required: true
          type: integer
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
      security:
         - marketplacecore_auth:
           - read_admin
    put:
      description: Create User
      parameters:
        - name: userUUID
          in: query
          description: Web System userUUID or Admin.
          required: true
          type: string
        - name: userFirstName
          in: query
          description: system client userid
          required: true
          type: string
        - name: userLastName
          in: query
          description: system client userid
          required: true
          type: string
        - name: userEmailAddress
          in: query
          description: system client userid
          required: true
          type: string
        - name: thumbnail
          in: query
          description: system client userid
          required: true
          type: string
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
      security:
      - marketplacecore_auth: 
           - write_services
              
  /users/findByID:
    get:
      description: get user by given UserUUID
      parameters:
        - name: userUUID
          in: query
          description: searched userUUID
          required: true
          type: integer
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
      security:
      - marketplacecore_auth:
          - read_services 
              
  /users/findByName:
    get:
      description: gets Users with given First OR Last Name
      parameters:
        - name: userFirstName
          in: query
          description: system client userid
          required: false
          type: integer
        - name: userLastName
          in: query
          description: system client userid
          required: false
          type: integer
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
      security:
      - marketplacecore_auth:
          - read_services 
              
  /technologydata:
    get:
      description: gets all technology data
      parameters:
        - name: userUUID
          in: query
          description: system client userid
          required: true
          type: integer
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/TechnologyData'
      security:
      - marketplacecore_auth:
          - read_services 
    put:
      description: Create a new Technology Data
      parameters:
        - name: userUUID
          in: query
          description: system client userid
          required: true
          type: integer
        - name: technologydataname
          in: query 
          description: the tecnology data name. This is unique name. In case the name already exists the request will fail
          required: true
          type: string
        - name: technologydata
          in: query 
          description: the technology data itself
          required: true
          type: string
        - name: technologydatadescription
          in: query 
          description: some description to technology data
          required: true
          type: string
        - name: licensefee
          in: query 
          description: the cost for one technology data unit
          required: true
          type: number
        - name: technologyUUID
          in: query 
          description: the id of the technology to be used
          required: true
          type: string
        - name: tagscomponentlist
          in: body 
          description: a list with the tagName and ComponenteID for the technology data
          required: true
          schema:
            type: array
            items: 
               $ref: '#/definitions/List'
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/TechnologyData'
      security:
      - marketplacecore_auth:
          - write_public
  
  /technologydata/findByID:
    get:
      description: get the technology data for the given id
      parameters:
        - name: userUUID
          in: query
          description: system client userid
          required: true
          type: integer
        - name: technologyUUID
          in: query
          description: the searched technologyUUID
          required: true
          type: string
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/TechnologyData'
      security:
      - marketplacecore_auth:
          - read_services
          
  /technologydata/findByName:
    get:
      description: get the technology data for the given name
      parameters:
        - name: userUUID
          in: query
          description: system client userid
          required: true
          type: integer
        - name: technologyName
          in: query
          description: Name of the searched technology
          required: true
          type: string
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/TechnologyData'
      security:
      - marketplacecore_auth:
          - read_services
              
  /technologydata/findByParams:
    get:
      summary: Find Technology Data by differents Parameters
      description: Multiple Parameters can be provide with coma separated strings. 
      produces: 
        - application/json
      parameters:
        - name: userUUID
          in: query
          description: userid
          required: true
          type: integer
        - in: query
          name: tags
          description: Tags to filter by
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
        - in: query
          name: components
          description: Components to filter by
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
        - in: query
          name: technologies
          description: Technologies to filter by
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
        - in: query
          name: attributes
          description: Attributes to filter by
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
      responses: 
        "200":
          description: sucessful operation
          schema: 
            type: array
            items: 
              $ref: '#/definitions/TechnologyData'
      security:
         - marketplacecore_auth:
           - read_services
  /tags:
    get:
      description: gets all tags
      parameters:
        - name: userUUID
          in: query
          description: system client userid
          required: true
          type: integer
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Tags'
      security:
         - marketplacecore_auth:
           - read_public
            
  /tags/findByID:
    get:
      description: gets all tags
      parameters:
        - name: userUUID
          in: query
          description: system client userid
          required: true
          type: integer
        - name: tagID
          in: query
          description: the searched tagID
          required: true
          type: integer
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Tags'
      security:
         - marketplacecore_auth:
           - read_services
  
  /tags/findByName:
    get:
      description: gets all tags
      parameters:
        - name: userUUID
          in: query
          description: system client userid
          required: true
          type: integer
        - name: tagName
          in: query
          description: Name of the tag to be searched
          required: true
          type: string
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Tags'
      security:
         - marketplacecore_auth:
           - read_services
  
  /components:
    get:
      description: gets all components
      parameters:
        - name: userUUID
          in: query
          description: system client userid
          required: true
          type: integer
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Components'
      security:
         - marketplacecore_auth:
           - read_public
              
  /components/findByID:
    get:
      description: gets all components
      parameters:
        - name: userUUID
          in: query
          description: system client userid
          required: true
          type: integer
        - name: componentUUID
          in: query
          description: ComponentUUID to be searched
          required: true
          type: integer
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Components'
      security:
         - marketplacecore_auth:
           - read_services
              
  /components/findByName:
    get:
      description: gets all components
      parameters:
        - name: userUUID
          in: query
          description: system client userid
          required: true
          type: integer
        - name: componentName
          in: query
          description: Componenten name to be searched
          required: true
          type: string
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Components'
      security:
         - marketplacecore_auth:
           - read_public
  
  /technologies:
    get:
      description: gets all technologies
      parameters:
        - name: userUUID
          in: query
          description: system client userid
          required: true
          type: integer
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Technologies'
      security:
         - marketplacecore_auth:
           - read_services
    put:
      description: Create a new technology
      parameters:
        - name: userUUID
          in: query
          description: system client userid
          required: true
          type: integer
        - name: technologyName
          in: query
          description: Name of the new technology. The technology name has to be unique.
          required: true
          type: string
        - name: technologydescription
          in: query
          description: A description of the new technology.
          required: true
          type: string
      responses:
        '200':
          description: Successful response
          schema:
            type: array
            items:
              $ref: '#/definitions/Technologies'
      security:
         - marketplacecore_auth:
           - read_services
 
  /technologies/findByID:
      get:
        description: gets all technologies
        parameters:
          - name: userUUID
            in: query
            description: system client userid
            required: true
            type: integer
          - name: technologyUUID
            in: query
            description: TechnologyID to be searched
            required: true
            type: integer
        responses:
          '200':
            description: Successful response
            schema:
              type: array
              items:
                $ref: '#/definitions/Technologies'
        security:
         - marketplacecore_auth:
           - read_services
           
  /technologies/findByName:
      get:
        description: gets all technologies
        parameters:
          - name: userUUID
            in: query
            description: system client userid
            required: true
            type: integer
          - name: technologyName
            in: query
            description: Technology name to be searched
            required: true
            type: string
        responses:
          '200':
            description: Successful response
            schema:
              type: array
              items:
                $ref: '#/definitions/Technologies'
        security:
         - marketplacecore_auth:
           - read_public 
    
securityDefinitions: 
  marketplacecore_auth:
    type: oauth2
    authorizationUrl: to be defined
    flow: implicit
    scopes:
      write_public: public users write right 
      read_public: public users write right
      read_admin: admin read right       
      write_admin: admin write right
      write_services: web system and machine services right
      read_services: web system and machine services right 
      
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
      firstname:
        type: string
      lastname:
        type: string
      email:
        type: string
      thumbnail:
        type: string
        
  TechnologyData:
    type: object
    properties:
      technologydataid:
        type: integer
      technologydataname:
        type: string
      technologydatadescription:
        type: string
      licensefee:
        type: number 
      createdat: 
       type: string
      createdby:
       type: string
      updatedat: 
       type: string
      updatedby: 
       type: string
  
  Tags:
   type: object
   properties:
     tagid: 
      type: integer
     tagname:
      type: string
     createdat: 
      type: string
     createdby:
      type: string
     updatedat: 
      type: string
     updatedby: 
      type: string
  
  Components:
   type: object
   properties:
     componentid: 
      type: integer
     componentname:
      type: string
     componentparentid:
      type: integer
     componentdescription:
      type: string
     createdat: 
      type: string
     createdby:
      type: string
     updatedat: 
      type: string
     updatedby: 
      type: string
      
  Technologies:
   type: object
   properties:
     technologyid: 
      type: integer
     technologyname:
      type: string
     technologydescription:
      type: string
     createdat: 
      type: string
     createdby:
      type: string
     updatedat: 
      type: string
     updatedby: 
      type: string
      
  List:
   type: object
   properties:
     tagName: 
      type: string 
     componentID: 
      type: integer