DO
$$

BEGIN
-- Ultimaker PLA Red
perform public.setcomponent('Ultimaker PLA Red', 'PLA', 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '9cfe5bf1-bdc5-4beb-871a-52c70777842d'::uuid WHERE componentdescription = 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PLA Red');
UPDATE components SET displaycolor = '#bb1e10' WHERE componentdescription = 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PLA Red');
-- Ultimaker TPU 95A Blue
perform public.setcomponent('Ultimaker TPU 95A Blue', 'PLA', 'Wear and tear resistant. TPU features a Shore-A hardness of 95 and an elongation of up to 580% at break. Suitable for applications that require slight flexibility, wear and tear, and chemical resistance.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '5f4a826c-7bfe-460f-8650-a9178b180d34'::uuid WHERE componentdescription = 'Wear and tear resistant. TPU features a Shore-A hardness of 95 and an elongation of up to 580% at break. Suitable for applications that require slight flexibility, wear and tear, and chemical resistance.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker TPU 95A Blue');
UPDATE components SET displaycolor = '#00387b' WHERE componentdescription = 'Wear and tear resistant. TPU features a Shore-A hardness of 95 and an elongation of up to 580% at break. Suitable for applications that require slight flexibility, wear and tear, and chemical resistance.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker TPU 95A Blue');
-- Ultimaker CPE+ White
perform public.setcomponent('Ultimaker CPE+ White', 'PLA', 'Chemically resistant and tough. CPE+ is chemically inert, tough, dimensionally stable and handles temperatures up to 100ºC.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '6df69b13-2d96-4a69-a297-aedba667e710'::uuid WHERE componentdescription = 'Chemically resistant and tough. CPE+ is chemically inert, tough, dimensionally stable and handles temperatures up to 100ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker CPE+ White');
UPDATE components SET displaycolor = '#f1ece1' WHERE componentdescription = 'Chemically resistant and tough. CPE+ is chemically inert, tough, dimensionally stable and handles temperatures up to 100ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker CPE+ White');
-- Ultimaker PC Transparent
perform public.setcomponent('Ultimaker PC Transparent', 'PLA', 'Strong, tough and temperature resistant. PC offers a great print quality, heat resistance up to 110ºC, mechanical strength and toughness.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '8a38a3e9-ecf7-4a7d-a6a9-e7ac35102968'::uuid WHERE componentdescription = 'Strong, tough and temperature resistant. PC offers a great print quality, heat resistance up to 110ºC, mechanical strength and toughness.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PC Transparent');
UPDATE components SET displaycolor = '#d0d0d0' WHERE componentdescription = 'Strong, tough and temperature resistant. PC offers a great print quality, heat resistance up to 110ºC, mechanical strength and toughness.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PC Transparent');
-- Generic ABS Generic
perform public.setcomponent('Generic ABS Generic', 'PLA', 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '60636bb4-518f-42e7-8237-fe77b194ebe0'::uuid WHERE componentdescription = 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Generic ABS Generic');
UPDATE components SET displaycolor = '#8cb219' WHERE componentdescription = 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Generic ABS Generic');
-- Ultimaker PLA Magenta
perform public.setcomponent('Ultimaker PLA Magenta', 'PLA', 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = 'fe3982c8-58f4-4d86-9ac0-9ff7a3ab9cbc'::uuid WHERE componentdescription = 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PLA Magenta');
UPDATE components SET displaycolor = '#bc4077' WHERE componentdescription = 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PLA Magenta');
-- Generic PP Generic
perform public.setcomponent('Generic PP Generic', 'PLA', 'Fatigue and chemical resistant. Polypropylene offers excellent temperature, chemical and fatigue resistance. Its toughness and low friction make it a perfect choice for prototyping and creating durable end-use models.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = 'aa22e9c7-421f-4745-afc2-81851694394a'::uuid WHERE componentdescription = 'Fatigue and chemical resistant. Polypropylene offers excellent temperature, chemical and fatigue resistance. Its toughness and low friction make it a perfect choice for prototyping and creating durable end-use models.' AND textid IN (SELECT textid FROM translations WHERE value = 'Generic PP Generic');
UPDATE components SET displaycolor = '#85f9de' WHERE componentdescription = 'Fatigue and chemical resistant. Polypropylene offers excellent temperature, chemical and fatigue resistance. Its toughness and low friction make it a perfect choice for prototyping and creating durable end-use models.' AND textid IN (SELECT textid FROM translations WHERE value = 'Generic PP Generic');
-- Ultimaker PLA White
perform public.setcomponent('Ultimaker PLA White', 'PLA', 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = 'e509f649-9fe6-4b14-ac45-d441438cb4ef'::uuid WHERE componentdescription = 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PLA White');
UPDATE components SET displaycolor = '#f1ece1' WHERE componentdescription = 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PLA White');
-- Ultimaker PLA Orange
perform public.setcomponent('Ultimaker PLA Orange', 'PLA', 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = 'd9549dba-b9df-45b9-80a5-f7140a9a2f34'::uuid WHERE componentdescription = 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PLA Orange');
UPDATE components SET displaycolor = '#ed6b21' WHERE componentdescription = 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PLA Orange');
-- Ultimaker PLA Silver Metallic
perform public.setcomponent('Ultimaker PLA Silver Metallic', 'PLA', 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '0e01be8c-e425-4fb1-b4a3-b79f255f1db9'::uuid WHERE componentdescription = 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PLA Silver Metallic');
UPDATE components SET displaycolor = '#a1a1a0' WHERE componentdescription = 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PLA Silver Metallic');
-- Ultimaker PC Black
perform public.setcomponent('Ultimaker PC Black', 'PLA', 'Strong, tough and temperature resistant. PC offers a great print quality, heat resistance up to 110ºC, mechanical strength and toughness.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = 'e92b1f0b-a069-4969-86b4-30127cfb6f7b'::uuid WHERE componentdescription = 'Strong, tough and temperature resistant. PC offers a great print quality, heat resistance up to 110ºC, mechanical strength and toughness.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PC Black');
UPDATE components SET displaycolor = '#0e0e10' WHERE componentdescription = 'Strong, tough and temperature resistant. PC offers a great print quality, heat resistance up to 110ºC, mechanical strength and toughness.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PC Black');
-- Ultimaker Tough PLA Green
perform public.setcomponent('Ultimaker Tough PLA Green', 'PLA', '', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '6d71f4ad-29ab-4b50-8f65-22d99af294dd'::uuid WHERE componentdescription = '' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker Tough PLA Green');
UPDATE components SET displaycolor = '#00a95c' WHERE componentdescription = '' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker Tough PLA Green');
-- Generic CPE+ Generic
perform public.setcomponent('Generic CPE+ Generic', 'PLA', 'Chemically resistant and tough. CPE+ is chemically inert, tough, dimensionally stable and handles temperatures up to 100ºC.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = 'e2409626-b5a0-4025-b73e-b58070219259'::uuid WHERE componentdescription = 'Chemically resistant and tough. CPE+ is chemically inert, tough, dimensionally stable and handles temperatures up to 100ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Generic CPE+ Generic');
UPDATE components SET displaycolor = '#3633F2' WHERE componentdescription = 'Chemically resistant and tough. CPE+ is chemically inert, tough, dimensionally stable and handles temperatures up to 100ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Generic CPE+ Generic');
-- Ultimaker CPE Dark Grey
perform public.setcomponent('Ultimaker CPE Dark Grey', 'PLA', 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '10961c00-3caf-48e9-a598-fa805ada1e8d'::uuid WHERE componentdescription = 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker CPE Dark Grey');
UPDATE components SET displaycolor = '#4f5250' WHERE componentdescription = 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker CPE Dark Grey');
-- Ultimaker CPE Black
perform public.setcomponent('Ultimaker CPE Black', 'PLA', 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = 'a8955dc3-9d7e-404d-8c03-0fd6fee7f22d'::uuid WHERE componentdescription = 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker CPE Black');
UPDATE components SET displaycolor = '#2a292a' WHERE componentdescription = 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker CPE Black');
-- Generic PLA Generic
perform public.setcomponent('Generic PLA Generic', 'PLA', 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '506c9f0d-e3aa-4bd4-b2d2-23e2425b1aa9'::uuid WHERE componentdescription = 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.' AND textid IN (SELECT textid FROM translations WHERE value = 'Generic PLA Generic');
UPDATE components SET displaycolor = '#ffc924' WHERE componentdescription = 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.' AND textid IN (SELECT textid FROM translations WHERE value = 'Generic PLA Generic');
-- Ultimaker PC White
perform public.setcomponent('Ultimaker PC White', 'PLA', 'Strong, tough and temperature resistant. PC offers a great print quality, heat resistance up to 110ºC, mechanical strength and toughness.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '5e786b05-a620-4a87-92d0-f02becc1ff98'::uuid WHERE componentdescription = 'Strong, tough and temperature resistant. PC offers a great print quality, heat resistance up to 110ºC, mechanical strength and toughness.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PC White');
UPDATE components SET displaycolor = '#ecece7' WHERE componentdescription = 'Strong, tough and temperature resistant. PC offers a great print quality, heat resistance up to 110ºC, mechanical strength and toughness.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PC White');
-- Ultimaker CPE Blue
perform public.setcomponent('Ultimaker CPE Blue', 'PLA', 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '4d816290-ce2e-40e0-8dc8-3f702243131e'::uuid WHERE componentdescription = 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker CPE Blue');
UPDATE components SET displaycolor = '#00a3e0' WHERE componentdescription = 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker CPE Blue');
-- Generic Breakaway Generic
perform public.setcomponent('Generic Breakaway Generic', 'PLA', 'Breakaway Material. Breakaway is a matching support material for PLA, ABS, CPE, CPE+, and Nylon', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '7e6207c4-22ff-441a-b261-ff89f166d6a0'::uuid WHERE componentdescription = 'Breakaway Material. Breakaway is a matching support material for PLA, ABS, CPE, CPE+, and Nylon' AND textid IN (SELECT textid FROM translations WHERE value = 'Generic Breakaway Generic');
UPDATE components SET displaycolor = '#f1ece1' WHERE componentdescription = 'Breakaway Material. Breakaway is a matching support material for PLA, ABS, CPE, CPE+, and Nylon' AND textid IN (SELECT textid FROM translations WHERE value = 'Generic Breakaway Generic');
-- Ultimaker ABS Blue
perform public.setcomponent('Ultimaker ABS Blue', 'PLA', 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '7c9575a6-c8d6-40ec-b3dd-18d7956bfaae'::uuid WHERE componentdescription = 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker ABS Blue');
UPDATE components SET displaycolor = '#00387b' WHERE componentdescription = 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker ABS Blue');
-- Ultimaker CPE+ Black
perform public.setcomponent('Ultimaker CPE+ Black', 'PLA', 'Chemically resistant and tough. CPE+ is chemically inert, tough, dimensionally stable and handles temperatures up to 100ºC.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '1aca047a-42df-497c-abfb-0e9cb85ead52'::uuid WHERE componentdescription = 'Chemically resistant and tough. CPE+ is chemically inert, tough, dimensionally stable and handles temperatures up to 100ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker CPE+ Black');
UPDATE components SET displaycolor = '#0e0e10' WHERE componentdescription = 'Chemically resistant and tough. CPE+ is chemically inert, tough, dimensionally stable and handles temperatures up to 100ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker CPE+ Black');
-- Generic Nylon Generic
perform public.setcomponent('Generic Nylon Generic', 'PLA', 'Nylon is strong, abrasion-resistant, durable and engineered for low moisture sensitivity.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '28fb4162-db74-49e1-9008-d05f1e8bef5c'::uuid WHERE componentdescription = 'Nylon is strong, abrasion-resistant, durable and engineered for low moisture sensitivity.' AND textid IN (SELECT textid FROM translations WHERE value = 'Generic Nylon Generic');
UPDATE components SET displaycolor = '#3DF266' WHERE componentdescription = 'Nylon is strong, abrasion-resistant, durable and engineered for low moisture sensitivity.' AND textid IN (SELECT textid FROM translations WHERE value = 'Generic Nylon Generic');
-- Ultimaker TPU 95A Red
perform public.setcomponent('Ultimaker TPU 95A Red', 'PLA', 'Wear and tear resistant. TPU features a Shore-A hardness of 95 and an elongation of up to 580% at break. Suitable for applications that require slight flexibility, wear and tear, and chemical resistance.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '07a4547f-d21f-41a0-8eee-bc92125221b3'::uuid WHERE componentdescription = 'Wear and tear resistant. TPU features a Shore-A hardness of 95 and an elongation of up to 580% at break. Suitable for applications that require slight flexibility, wear and tear, and chemical resistance.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker TPU 95A Red');
UPDATE components SET displaycolor = '#a63437' WHERE componentdescription = 'Wear and tear resistant. TPU features a Shore-A hardness of 95 and an elongation of up to 580% at break. Suitable for applications that require slight flexibility, wear and tear, and chemical resistance.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker TPU 95A Red');
-- Ultimaker ABS Green
perform public.setcomponent('Ultimaker ABS Green', 'PLA', 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '3400c0d1-a4e3-47de-a444-7b704f287171'::uuid WHERE componentdescription = 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker ABS Green');
UPDATE components SET displaycolor = '#61993b' WHERE componentdescription = 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker ABS Green');
-- Ultimaker ABS Yellow
perform public.setcomponent('Ultimaker ABS Yellow', 'PLA', 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = 'e873341d-d9b8-45f9-9a6f-5609e1bcff68'::uuid WHERE componentdescription = 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker ABS Yellow');
UPDATE components SET displaycolor = '#f7b500' WHERE componentdescription = 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker ABS Yellow');
-- Ultimaker PLA Black
perform public.setcomponent('Ultimaker PLA Black', 'PLA', 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '3ee70a86-77d8-4b87-8005-e4a1bc57d2ce'::uuid WHERE componentdescription = 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PLA Black');
UPDATE components SET displaycolor = '#0e0e10' WHERE componentdescription = 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PLA Black');
-- Ultimaker ABS White
perform public.setcomponent('Ultimaker ABS White', 'PLA', 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '5253a75a-27dc-4043-910f-753ae11bc417'::uuid WHERE componentdescription = 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker ABS White');
UPDATE components SET displaycolor = '#ecece7' WHERE componentdescription = 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker ABS White');
-- Ultimaker Nylon Black
perform public.setcomponent('Ultimaker Nylon Black', 'PLA', 'Nylon is strong, abrasion-resistant, durable and engineered for low moisture sensitivity.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = 'c64c2dbe-5691-4363-a7d9-66b2dc12837f'::uuid WHERE componentdescription = 'Nylon is strong, abrasion-resistant, durable and engineered for low moisture sensitivity.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker Nylon Black');
UPDATE components SET displaycolor = '#27292b' WHERE componentdescription = 'Nylon is strong, abrasion-resistant, durable and engineered for low moisture sensitivity.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker Nylon Black');
-- Ultimaker ABS Black
perform public.setcomponent('Ultimaker ABS Black', 'PLA', 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '2f9d2279-9b0e-4765-bf9b-d1e1e13f3c49'::uuid WHERE componentdescription = 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker ABS Black');
UPDATE components SET displaycolor = '#2a292a' WHERE componentdescription = 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker ABS Black');
-- Ultimaker CPE White
perform public.setcomponent('Ultimaker CPE White', 'PLA', 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '881c888e-24fb-4a64-a4ac-d5c95b096cd7'::uuid WHERE componentdescription = 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker CPE White');
UPDATE components SET displaycolor = '#f1ece1' WHERE componentdescription = 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker CPE White');
-- Generic PVA Generic
perform public.setcomponent('Generic PVA Generic', 'PLA', 'Water soluble support material. PVA is a matching support material for PLA, CPE and Nylon.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '86a89ceb-4159-47f6-ab97-e9953803d70f'::uuid WHERE componentdescription = 'Water soluble support material. PVA is a matching support material for PLA, CPE and Nylon.' AND textid IN (SELECT textid FROM translations WHERE value = 'Generic PVA Generic');
UPDATE components SET displaycolor = '#a32bcc' WHERE componentdescription = 'Water soluble support material. PVA is a matching support material for PLA, CPE and Nylon.' AND textid IN (SELECT textid FROM translations WHERE value = 'Generic PVA Generic');
-- Ultimaker CPE Yellow
perform public.setcomponent('Ultimaker CPE Yellow', 'PLA', 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = 'b9176a2a-7a0f-4821-9f29-76d882a88682'::uuid WHERE componentdescription = 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker CPE Yellow');
UPDATE components SET displaycolor = '#f6b600' WHERE componentdescription = 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker CPE Yellow');
-- Ultimaker PLA Yellow
perform public.setcomponent('Ultimaker PLA Yellow', 'PLA', 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '9c1959d0-f597-46ec-9131-34020c7a54fc'::uuid WHERE componentdescription = 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PLA Yellow');
UPDATE components SET displaycolor = '#f9a800' WHERE componentdescription = 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PLA Yellow');
-- Generic PC Generic
perform public.setcomponent('Generic PC Generic', 'PLA', 'Strong, tough and temperature resistant. PC offers a great print quality, heat resistance up to 110ºC, mechanical strength and toughness.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '98c05714-bf4e-4455-ba27-57d74fe331e4'::uuid WHERE componentdescription = 'Strong, tough and temperature resistant. PC offers a great print quality, heat resistance up to 110ºC, mechanical strength and toughness.' AND textid IN (SELECT textid FROM translations WHERE value = 'Generic PC Generic');
UPDATE components SET displaycolor = '#F29030' WHERE componentdescription = 'Strong, tough and temperature resistant. PC offers a great print quality, heat resistance up to 110ºC, mechanical strength and toughness.' AND textid IN (SELECT textid FROM translations WHERE value = 'Generic PC Generic');
-- Ultimaker CPE Green
perform public.setcomponent('Ultimaker CPE Green', 'PLA', 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '7ff6d2c8-d626-48cd-8012-7725fa537cc9'::uuid WHERE componentdescription = 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker CPE Green');
UPDATE components SET displaycolor = '#78be20' WHERE componentdescription = 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker CPE Green');
-- Ultimaker CPE Light Grey
perform public.setcomponent('Ultimaker CPE Light Grey', 'PLA', 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '173a7bae-5e14-470e-817e-08609c61e12b'::uuid WHERE componentdescription = 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker CPE Light Grey');
UPDATE components SET displaycolor = '#c5c7c4' WHERE componentdescription = 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker CPE Light Grey');
-- Ultimaker Breakaway White
perform public.setcomponent('Ultimaker Breakaway White', 'PLA', 'Breakaway Material. Breakaway is a matching support material for PLA, ABS, CPE, CPE+, and Nylon', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '7e6207c4-22ff-441a-b261-ff89f166d5f9'::uuid WHERE componentdescription = 'Breakaway Material. Breakaway is a matching support material for PLA, ABS, CPE, CPE+, and Nylon' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker Breakaway White');
UPDATE components SET displaycolor = '#f1ece1' WHERE componentdescription = 'Breakaway Material. Breakaway is a matching support material for PLA, ABS, CPE, CPE+, and Nylon' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker Breakaway White');
-- Ultimaker ABS Orange
perform public.setcomponent('Ultimaker ABS Orange', 'PLA', 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '0b4ca6ef-eac8-4b23-b3ca-5f21af00e54f'::uuid WHERE componentdescription = 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker ABS Orange');
UPDATE components SET displaycolor = '#ed6b21' WHERE componentdescription = 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker ABS Orange');
-- Ultimaker PLA Green
perform public.setcomponent('Ultimaker PLA Green', 'PLA', 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '2433b8fb-dcd6-4e36-9cd5-9f4ee551c04c'::uuid WHERE componentdescription = 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PLA Green');
UPDATE components SET displaycolor = '#61993b' WHERE componentdescription = 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PLA Green');
-- Ultimaker TPU 95A White
perform public.setcomponent('Ultimaker TPU 95A White', 'PLA', 'Wear and tear resistant. TPU features a Shore-A hardness of 95 and an elongation of up to 580% at break. Suitable for applications that require slight flexibility, wear and tear, and chemical resistance.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '6a2573e6-c8ee-4c66-8029-3ebb3d5adc5b'::uuid WHERE componentdescription = 'Wear and tear resistant. TPU features a Shore-A hardness of 95 and an elongation of up to 580% at break. Suitable for applications that require slight flexibility, wear and tear, and chemical resistance.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker TPU 95A White');
UPDATE components SET displaycolor = '#f1ece1' WHERE componentdescription = 'Wear and tear resistant. TPU features a Shore-A hardness of 95 and an elongation of up to 580% at break. Suitable for applications that require slight flexibility, wear and tear, and chemical resistance.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker TPU 95A White');
-- Ultimaker Tough PLA White
perform public.setcomponent('Ultimaker Tough PLA White', 'PLA', '', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '851427a0-0c9a-4d7c-a9a8-5cc92f84af1f'::uuid WHERE componentdescription = '' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker Tough PLA White');
UPDATE components SET displaycolor = '#ecece7' WHERE componentdescription = '' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker Tough PLA White');
-- Ultimaker TPU 95A Black
perform public.setcomponent('Ultimaker TPU 95A Black', 'PLA', 'Wear and tear resistant. TPU features a Shore-A hardness of 95 and an elongation of up to 580% at break. Suitable for applications that require slight flexibility, wear and tear, and chemical resistance.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = 'eff40bcf-588d-420d-a3bc-a5ffd8c7f4b3'::uuid WHERE componentdescription = 'Wear and tear resistant. TPU features a Shore-A hardness of 95 and an elongation of up to 580% at break. Suitable for applications that require slight flexibility, wear and tear, and chemical resistance.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker TPU 95A Black');
UPDATE components SET displaycolor = '#0e0e10' WHERE componentdescription = 'Wear and tear resistant. TPU features a Shore-A hardness of 95 and an elongation of up to 580% at break. Suitable for applications that require slight flexibility, wear and tear, and chemical resistance.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker TPU 95A Black');
-- Ultimaker PLA Blue
perform public.setcomponent('Ultimaker PLA Blue', 'PLA', 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '44a029e6-e31b-4c9e-a12f-9282e29a92ff'::uuid WHERE componentdescription = 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PLA Blue');
UPDATE components SET displaycolor = '#00387b' WHERE componentdescription = 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PLA Blue');
-- Ultimaker Tough PLA Red
perform public.setcomponent('Ultimaker Tough PLA Red', 'PLA', '', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '2db25566-9a91-4145-84a5-46c90ed22bdf'::uuid WHERE componentdescription = '' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker Tough PLA Red');
UPDATE components SET displaycolor = '#de4343' WHERE componentdescription = '' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker Tough PLA Red');
-- Ultimaker CPE Red
perform public.setcomponent('Ultimaker CPE Red', 'PLA', 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '00181d6c-7024-479a-8eb7-8a2e38a2619a'::uuid WHERE componentdescription = 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker CPE Red');
UPDATE components SET displaycolor = '#c8102e' WHERE componentdescription = 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker CPE Red');
-- Generic CPE Generic
perform public.setcomponent('Generic CPE Generic', 'PLA', 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '12f41353-1a33-415e-8b4f-a775a6c70cc6'::uuid WHERE componentdescription = 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Generic CPE Generic');
UPDATE components SET displaycolor = '#159499' WHERE componentdescription = 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Generic CPE Generic');
-- Generic TPU 95A Generic
perform public.setcomponent('Generic TPU 95A Generic', 'PLA', 'Wear and tear resistant. TPU features a Shore-A hardness of 95 and an elongation of up to 580% at break. Suitable for applications that require slight flexibility, wear and tear, and chemical resistance.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '1d52b2be-a3a2-41de-a8b1-3bcdb5618695'::uuid WHERE componentdescription = 'Wear and tear resistant. TPU features a Shore-A hardness of 95 and an elongation of up to 580% at break. Suitable for applications that require slight flexibility, wear and tear, and chemical resistance.' AND textid IN (SELECT textid FROM translations WHERE value = 'Generic TPU 95A Generic');
UPDATE components SET displaycolor = '#B22744' WHERE componentdescription = 'Wear and tear resistant. TPU features a Shore-A hardness of 95 and an elongation of up to 580% at break. Suitable for applications that require slight flexibility, wear and tear, and chemical resistance.' AND textid IN (SELECT textid FROM translations WHERE value = 'Generic TPU 95A Generic');
-- Generic Tough PLA Generic
perform public.setcomponent('Generic Tough PLA Generic', 'PLA', 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '9d5d2d7c-4e77-441c-85a0-e9eefd4aa68c'::uuid WHERE componentdescription = 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.' AND textid IN (SELECT textid FROM translations WHERE value = 'Generic Tough PLA Generic');
UPDATE components SET displaycolor = '#ffc9f0' WHERE componentdescription = 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.' AND textid IN (SELECT textid FROM translations WHERE value = 'Generic Tough PLA Generic');
-- Ultimaker Tough PLA Black
perform public.setcomponent('Ultimaker Tough PLA Black', 'PLA', '', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '03f24266-0291-43c2-a6da-5211892a2699'::uuid WHERE componentdescription = '' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker Tough PLA Black');
UPDATE components SET displaycolor = '#2a292a' WHERE componentdescription = '' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker Tough PLA Black');
-- Ultimaker CPE Transparent
perform public.setcomponent('Ultimaker CPE Transparent', 'PLA', 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = 'bd0d9eb3-a920-4632-84e8-dcd6086746c5'::uuid WHERE componentdescription = 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker CPE Transparent');
UPDATE components SET displaycolor = '#d0d0d0' WHERE componentdescription = 'Chemically resistant and tough. CPE is chemically inert, tough, dimensionally stable and handles temperatures up to 70ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker CPE Transparent');
-- Ultimaker PLA Pearl-White
perform public.setcomponent('Ultimaker PLA Pearl-White', 'PLA', 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = 'd9fc79db-82c3-41b5-8c99-33b3747b8fb3'::uuid WHERE componentdescription = 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PLA Pearl-White');
UPDATE components SET displaycolor = '#e3d9c6' WHERE componentdescription = 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PLA Pearl-White');
-- Ultimaker Nylon Transparent
perform public.setcomponent('Ultimaker Nylon Transparent', 'PLA', 'Nylon is strong, abrasion-resistant, durable and engineered for low moisture sensitivity.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = 'e256615d-a04e-4f53-b311-114b90560af9'::uuid WHERE componentdescription = 'Nylon is strong, abrasion-resistant, durable and engineered for low moisture sensitivity.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker Nylon Transparent');
UPDATE components SET displaycolor = '#d0d0d0' WHERE componentdescription = 'Nylon is strong, abrasion-resistant, durable and engineered for low moisture sensitivity.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker Nylon Transparent');
-- Ultimaker CPE+ Transparent
perform public.setcomponent('Ultimaker CPE+ Transparent', 'PLA', 'Chemically resistant and tough. CPE+ is chemically inert, tough, dimensionally stable and handles temperatures up to 100ºC.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = 'a9c340fe-255f-4914-87f5-ec4fcb0c11ef'::uuid WHERE componentdescription = 'Chemically resistant and tough. CPE+ is chemically inert, tough, dimensionally stable and handles temperatures up to 100ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker CPE+ Transparent');
UPDATE components SET displaycolor = '#d0d0d0' WHERE componentdescription = 'Chemically resistant and tough. CPE+ is chemically inert, tough, dimensionally stable and handles temperatures up to 100ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker CPE+ Transparent');
-- Ultimaker PP Transparent
perform public.setcomponent('Ultimaker PP Transparent', 'PLA', 'Fatigue and chemical resistant. Polypropylene offers excellent temperature, chemical and fatigue resistance. Its toughness and low friction make it a perfect choice for prototyping and creating durable end-use models.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = 'c7005925-2a41-4280-8cdd-4029e3fe5253'::uuid WHERE componentdescription = 'Fatigue and chemical resistant. Polypropylene offers excellent temperature, chemical and fatigue resistance. Its toughness and low friction make it a perfect choice for prototyping and creating durable end-use models.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PP Transparent');
UPDATE components SET displaycolor = '#d0d0d0' WHERE componentdescription = 'Fatigue and chemical resistant. Polypropylene offers excellent temperature, chemical and fatigue resistance. Its toughness and low friction make it a perfect choice for prototyping and creating durable end-use models.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PP Transparent');
-- Ultimaker ABS Grey
perform public.setcomponent('Ultimaker ABS Grey', 'PLA', 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '8b75b775-d3f2-4d0f-8fb2-2a3dd53cf673'::uuid WHERE componentdescription = 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker ABS Grey');
UPDATE components SET displaycolor = '#52595d' WHERE componentdescription = 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker ABS Grey');
-- Ultimaker ABS Pearl Gold
perform public.setcomponent('Ultimaker ABS Pearl Gold', 'PLA', 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '7cbdb9ca-081a-456f-a6ba-f73e4e9cb856'::uuid WHERE componentdescription = 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker ABS Pearl Gold');
UPDATE components SET displaycolor = '#80643f' WHERE componentdescription = 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker ABS Pearl Gold');
-- Ultimaker ABS Silver Metallic
perform public.setcomponent('Ultimaker ABS Silver Metallic', 'PLA', 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '763c926e-a5f7-4ba0-927d-b4e038ea2735'::uuid WHERE componentdescription = 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker ABS Silver Metallic');
UPDATE components SET displaycolor = '#a1a1a0' WHERE componentdescription = 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker ABS Silver Metallic');
-- Ultimaker PLA Transparent
perform public.setcomponent('Ultimaker PLA Transparent', 'PLA', 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '532e8b3d-5fd4-4149-b936-53ada9bd6b85'::uuid WHERE componentdescription = 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PLA Transparent');
UPDATE components SET displaycolor = '#d0d0d0' WHERE componentdescription = 'Fast, safe and reliable printing. PLA is ideal for the fast and reliable printing of parts and prototypes with a great surface quality.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PLA Transparent');
-- Ultimaker PVA Natural
perform public.setcomponent('Ultimaker PVA Natural', 'PLA', 'Water soluble support material. PVA is a matching support material for PLA, CPE and Nylon.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = 'fe15ed8a-33c3-4f57-a2a7-b4b78a38c3cb'::uuid WHERE componentdescription = 'Water soluble support material. PVA is a matching support material for PLA, CPE and Nylon.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PVA Natural');
UPDATE components SET displaycolor = '#f5f2d1' WHERE componentdescription = 'Water soluble support material. PVA is a matching support material for PLA, CPE and Nylon.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker PVA Natural');
-- Ultimaker ABS Red
perform public.setcomponent('Ultimaker ABS Red', 'PLA', 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.', 'components', 'en', '{material}', '{ultimaker}', '67e6ceb8-c633-47a9-8c69-f55228cb9676', '{TechnologyAdmin}');
UPDATE components SET componentuuid = '5df7afa6-48bd-4c19-b314-839fe9f08f1f'::uuid WHERE componentdescription = 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker ABS Red');
UPDATE components SET displaycolor = '#bb1e10' WHERE componentdescription = 'Tough and durable. ABS is good for mechanical parts. It is impact resistant, dimensionally stable and handles temperatures up to 85ºC.' AND textid IN (SELECT textid FROM translations WHERE value = 'Ultimaker ABS Red');

END
$$;
